import type { Metadata } from "next";
import { playwriteFont, quicksandFont } from '@/app/fonts';
import { Footer } from "@/components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playwriteFont.variable} ${quicksandFont.variable} antialiased px-4 pt-8 sm:p-8 md:p-12 lg:p-16 xl:px-24 pb-8!`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
